set fenc=utf-8
set fencs=utf-8,usc-bom,euc-jp,gb18030,gbk,gb2312,cp936
set langmenu=zh_CN.UTF-8
set helplang=cn
set nocp
set number
set ai
set si
set tabstop=4
set sw=4
set ruler
set incsearch
set showmatch
set matchtime=5
set ignorecase
colorscheme darkblue
syntax on
set autoread
set completeopt=preview,menu 
